/**
 * CRM YTS — Roles & Permissions Matrix Constants
 * Single source of truth for authorization across API and UI.
 */

export const ROLES = {
  LEADERSHIP_VIEWER: 'leadership_viewer',
  CRM_ADMIN: 'crm_admin',
  DATA_STEWARD: 'data_steward',
  CS_OFFICER: 'cs_officer',
  EVENT_ADMIN: 'event_admin',
  FUNDRAISING_OFFICER: 'fundraising_officer',
  WAQF_OFFICER: 'waqf_officer',
  FINANCE_VERIFIER: 'finance_verifier',
  BROADCAST_OFFICER: 'broadcast_officer',
  AUDITOR: 'auditor',
} as const;

export type RoleCode = (typeof ROLES)[keyof typeof ROLES];

export const PERMISSIONS = {
  // Dashboard & Analytics
  DASHBOARD_VIEW: 'dashboard.view',
  REPORTS_VIEW: 'reports.view',
  REPORTS_FINANCE: 'reports.finance',

  // People / Jamaah
  PERSONS_LIST: 'persons.list',
  PERSONS_VIEW: 'persons.view',
  PERSONS_VIEW_SUMMARY: 'persons.view_summary',
  PERSONS_VIEW_OPERATIONAL: 'persons.view_operational',
  PERSONS_CREATE: 'persons.create',
  PERSONS_QUICK_CREATE: 'persons.quick_create',
  PERSONS_EDIT: 'persons.edit',
  PERSONS_MERGE: 'persons.merge',
  PERSONS_MERGE_REQUEST: 'persons.merge_request',
  PERSONS_DEDUP_REVIEW: 'persons.dedup_review',

  // Sensitive Notes
  SENSITIVE_NOTES_VIEW: 'sensitive_notes.view',
  SENSITIVE_NOTES_CREATE: 'sensitive_notes.create',
  SENSITIVE_NOTES_DELETE: 'sensitive_notes.delete',

  // Tags
  TAGS_MANAGE: 'tags.manage',
  TAGS_ASSIGN: 'tags.assign',

  // Events & Kajian
  EVENTS_VIEW: 'events.view',
  EVENTS_MANAGE: 'events.manage',
  ATTENDANCE_MANAGE: 'attendance.manage',
  ATTENDANCE_VIEW_SUMMARY: 'attendance.view_summary',
  ENGAGEMENT_VIEW: 'engagement.view',

  // Interactions & Tasks
  INTERACTIONS_VIEW: 'interactions.view',
  INTERACTIONS_CREATE: 'interactions.create',
  TASKS_VIEW_OWN: 'tasks.view_own',
  TASKS_VIEW_ALL: 'tasks.view_all',
  TASKS_CREATE: 'tasks.create',
  TASKS_UPDATE_OWN: 'tasks.update_own',
  TASKS_MANAGE_OWN: 'tasks.manage_own',
  TASKS_REASSIGN: 'tasks.reassign',

  // Donations
  DONORS_VIEW: 'donors.view',
  DONATIONS_LIST: 'donations.list',
  DONATIONS_VIEW_SUMMARY: 'donations.view_summary',
  DONATIONS_VIEW_UNVERIFIED: 'donations.view_unverified',
  DONATIONS_VIEW_DETAIL: 'donations.view_detail',
  DONATIONS_CREATE: 'donations.create',
  DONATIONS_VERIFY: 'donations.verify',
  DONATIONS_REJECT: 'donations.reject',
  DONATIONS_CORRECT_VERIFIED: 'donations.correct_verified',
  DONATIONS_RECONCILE: 'donations.reconcile',

  // Waqf
  WAQF_LIST: 'waqf.list',
  WAQF_VIEW_SUMMARY: 'waqf.view_summary',
  WAQF_VIEW_DETAIL: 'waqf.view',
  WAQF_FINANCIAL_VIEW: 'waqf.financial_view',
  WAQF_CREATE: 'waqf.create',
  WAQF_EDIT: 'waqf.edit',
  WAQF_TRANSITION: 'waqf.transition',
  WAQF_DOCUMENTS_MANAGE: 'waqf.documents.manage',

  // Data Quality & Governance
  DATA_QUALITY_MANAGE: 'data_quality.manage',
  DATA_EXPORT: 'data.export',

  // Audit
  AUDIT_VIEW: 'audit.view',
  AUDIT_VIEW_SUMMARY: 'audit.view_summary',
  AUDIT_VIEW_DETAIL: 'audit.view_detail',
  EXPORTS_VIEW_LOG: 'exports.view_log',

  // System Administration
  USERS_MANAGE: 'users.manage',
  ROLES_ASSIGN: 'roles.assign',
  SYSTEM_CONFIGURE: 'system.configure',

  // Broadcast & Segments (Non-MVP Ready)
  SEGMENTS_VIEW: 'segments.view',
  BROADCAST_DRAFT: 'broadcast.draft',
  BROADCAST_HISTORY: 'broadcast.history',
  COMMUNICATION_PREFERENCES_VIEW: 'communication_preferences.view',
} as const;

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

/**
 * Default permission mapping per role based on ROLES_PERMISSIONS.md
 */
export const ROLE_PERMISSIONS: Record<RoleCode, readonly PermissionCode[]> = {
  [ROLES.LEADERSHIP_VIEWER]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.PERSONS_VIEW_SUMMARY,
    PERMISSIONS.DONATIONS_VIEW_SUMMARY,
    PERMISSIONS.WAQF_VIEW_SUMMARY,
    PERMISSIONS.AUDIT_VIEW_SUMMARY,
  ],
  [ROLES.CRM_ADMIN]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.USERS_MANAGE,
    PERMISSIONS.ROLES_ASSIGN,
    PERMISSIONS.PERSONS_LIST,
    PERMISSIONS.PERSONS_VIEW,
    PERMISSIONS.PERSONS_CREATE,
    PERMISSIONS.PERSONS_EDIT,
    PERMISSIONS.PERSONS_MERGE,
    PERMISSIONS.PERSONS_QUICK_CREATE,
    PERMISSIONS.TAGS_MANAGE,
    PERMISSIONS.TAGS_ASSIGN,
    PERMISSIONS.SYSTEM_CONFIGURE,
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.AUDIT_VIEW_DETAIL,
    PERMISSIONS.DATA_QUALITY_MANAGE,
    PERMISSIONS.DATA_EXPORT,
    PERMISSIONS.EXPORTS_VIEW_LOG,
    PERMISSIONS.EVENTS_VIEW,
    PERMISSIONS.EVENTS_MANAGE,
    PERMISSIONS.ATTENDANCE_MANAGE,
    PERMISSIONS.ATTENDANCE_VIEW_SUMMARY,
    PERMISSIONS.ENGAGEMENT_VIEW,
    PERMISSIONS.INTERACTIONS_VIEW,
    PERMISSIONS.INTERACTIONS_CREATE,
    PERMISSIONS.TASKS_VIEW_ALL,
    PERMISSIONS.TASKS_VIEW_OWN,
    PERMISSIONS.TASKS_CREATE,
    PERMISSIONS.TASKS_MANAGE_OWN,
    PERMISSIONS.TASKS_REASSIGN,
    PERMISSIONS.DONORS_VIEW,
    PERMISSIONS.DONATIONS_LIST,
    PERMISSIONS.DONATIONS_VIEW_SUMMARY,
    PERMISSIONS.DONATIONS_VIEW_DETAIL,
    PERMISSIONS.DONATIONS_VIEW_UNVERIFIED,
    PERMISSIONS.DONATIONS_CREATE,
    PERMISSIONS.WAQF_LIST,
    PERMISSIONS.WAQF_VIEW_DETAIL,
    PERMISSIONS.WAQF_VIEW_SUMMARY,
    PERMISSIONS.WAQF_CREATE,
    PERMISSIONS.WAQF_EDIT,
    PERMISSIONS.WAQF_TRANSITION,
    PERMISSIONS.WAQF_DOCUMENTS_MANAGE,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.BROADCAST_HISTORY,
    PERMISSIONS.BROADCAST_DRAFT,
    PERMISSIONS.SEGMENTS_VIEW,
  ],
  [ROLES.DATA_STEWARD]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.PERSONS_LIST,
    PERMISSIONS.PERSONS_VIEW,
    PERMISSIONS.PERSONS_CREATE,
    PERMISSIONS.PERSONS_EDIT,
    PERMISSIONS.PERSONS_DEDUP_REVIEW,
    PERMISSIONS.PERSONS_MERGE_REQUEST,
    PERMISSIONS.PERSONS_MERGE,
    PERMISSIONS.TAGS_ASSIGN,
    PERMISSIONS.DATA_QUALITY_MANAGE,
  ],
  [ROLES.CS_OFFICER]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.PERSONS_LIST,
    PERMISSIONS.PERSONS_VIEW_OPERATIONAL,
    PERMISSIONS.INTERACTIONS_CREATE,
    PERMISSIONS.INTERACTIONS_VIEW,
    PERMISSIONS.TASKS_CREATE,
    PERMISSIONS.TASKS_UPDATE_OWN,
    PERMISSIONS.TASKS_VIEW_OWN,
    PERMISSIONS.ATTENDANCE_VIEW_SUMMARY,
  ],
  [ROLES.EVENT_ADMIN]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.EVENTS_VIEW,
    PERMISSIONS.EVENTS_MANAGE,
    PERMISSIONS.ATTENDANCE_MANAGE,
    PERMISSIONS.PERSONS_QUICK_CREATE,
    PERMISSIONS.PERSONS_VIEW_OPERATIONAL,
    PERMISSIONS.ENGAGEMENT_VIEW,
  ],
  [ROLES.FUNDRAISING_OFFICER]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.DONORS_VIEW,
    PERMISSIONS.DONATIONS_LIST,
    PERMISSIONS.DONATIONS_CREATE,
    PERMISSIONS.DONATIONS_VIEW_UNVERIFIED,
    PERMISSIONS.INTERACTIONS_CREATE,
    PERMISSIONS.INTERACTIONS_VIEW,
    PERMISSIONS.TASKS_MANAGE_OWN,
    PERMISSIONS.TASKS_VIEW_OWN,
    PERMISSIONS.SEGMENTS_VIEW,
  ],
  [ROLES.WAQF_OFFICER]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.WAQF_LIST,
    PERMISSIONS.WAQF_VIEW_DETAIL,
    PERMISSIONS.WAQF_CREATE,
    PERMISSIONS.WAQF_EDIT,
    PERMISSIONS.WAQF_TRANSITION,
    PERMISSIONS.WAQF_DOCUMENTS_MANAGE,
    PERMISSIONS.TASKS_MANAGE_OWN,
    PERMISSIONS.TASKS_VIEW_OWN,
  ],
  [ROLES.FINANCE_VERIFIER]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.DONATIONS_LIST,
    PERMISSIONS.DONATIONS_VIEW_DETAIL,
    PERMISSIONS.DONATIONS_VERIFY,
    PERMISSIONS.DONATIONS_REJECT,
    PERMISSIONS.DONATIONS_CORRECT_VERIFIED,
    PERMISSIONS.DONATIONS_RECONCILE,
    PERMISSIONS.REPORTS_FINANCE,
    PERMISSIONS.WAQF_FINANCIAL_VIEW,
  ],
  [ROLES.BROADCAST_OFFICER]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.SEGMENTS_VIEW,
    PERMISSIONS.BROADCAST_DRAFT,
    PERMISSIONS.BROADCAST_HISTORY,
    PERMISSIONS.COMMUNICATION_PREFERENCES_VIEW,
  ],
  [ROLES.AUDITOR]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.AUDIT_VIEW_DETAIL,
    PERMISSIONS.EXPORTS_VIEW_LOG,
    PERMISSIONS.REPORTS_VIEW,
  ],
};

/**
 * Helper to check if given roles contain a specific permission.
 */
export function hasPermission(roles: RoleCode[], permission: PermissionCode): boolean {
  for (const role of roles) {
    const permissions = ROLE_PERMISSIONS[role];
    if (permissions && permissions.includes(permission)) {
      return true;
    }
  }
  return false;
}
